### ISSUE TITLE
Bug: 4 Different Android OS versions and Still Crashing w/ Black Screen Error & Message

### ISSUE THREAD

**Issue by ghost** [ushahidi/Ushahidi_Android#113]
" have downloaded the android app of Ushahidi v 3.1.4 on my phone.
When I open my deployment the screen goes 'black' and then ushahidi shuts down with the error message : 
"Ushahidi has stopped unfortunately"
However, I am able to open other deployments (in my area) on my phone.
I have checked this behaviour on 4 different android phones with OS versions Ginger bread, ICS, Jelly bean. The page shut down on each device.'"

**Comment by ghost** [comment]
I am submitting this for fellow a Ushahidian, Manwinder, who has been trying since March 6 to do the above, however, he submitted this report on the Ushahidi forums for troubleshooting ( http://forums.ushahidi.com/forums/topic/android-application-shuts-down/ ) and facebook Ushahidi forum/group with no response.  If at all possible (I know you have a lot on your plates) this bug is needed to be addressed in a timely manner for him and his team to get sorted, as they are in need of deploying their map, but haven't been able to so because of technical issues, this will be one of 4 issues/reports I am filing on his behalf, with his permission.  If there are any questions concerning the android crash, or you need more information, I would be more than happy to ask & provide any additional information needed. (Have also read reports of earlier crashes on android device, and think this is still an issue.)

**Comment by eyedol** [comment]
@elle-espere -- Thanks for reporting. Looking into it.

**Comment by manwinder** [comment]
@eyedol  

Any updates on this ? Thanks

**Comment by eyedol** [comment]
@elle-espere and @manwinder  Any URL I can test this fix with?

**Comment by manwinder** [comment]
@eyedol 

https://indiaoye.crowdmap.com/

This is the link of my deployment 'India OYE'

You may please test the fix with this. Thanks !

**Comment by eyedol** [comment]
@manwinder  thanks

**Comment by eyedol** [comment]
Fixed

**Comment by manwinder** [comment]
I am afraid the problem has not yet been resolved.
I cannot open my deployment on my android phone still

Regards
Manwinder Singh
Contact - +91 99700 51851

**Comment by eyedol** [comment]
@manwinder  Funky. This loads for me without a problem. Which version of Android are you running?. 
Can you send me a log?
![Screenshot_2013-03-25-18-02-39](https://f.cloud.github.com/assets/73175/299414/af390564-957a-11e2-8f63-6ef2fafe4aab.png)

**Comment by manwinder** [comment]
@eyedol Strange, I still can't open it on my phone (Android 4.1.2). The stranger part is that I am able to open other maps in the sorrounding (For e.g. Mumbai Civic Issues) but not mine.

Please find attached 
1. Screen shot of the maps in my area including mine India OYE
   ![Screenshot_2013-03-26-07-16-33 1 ](https://f.cloud.github.com/assets/3960883/301127/bfb316ba-95bf-11e2-9382-192e89195399.png)
2. Screen shot of 'Ushahidi has stopped' when I open India OYE
   ![Screenshot_2013-03-26-07-15-58 1 ](https://f.cloud.github.com/assets/3960883/301130/e129d478-95bf-11e2-88e8-ceb250914fbf.png)
3. Screen shot of 'Mumbai Civic Issues' that I am able to open on the same device
   ![Screenshot_2013-03-26-08-07-33 1 ](https://f.cloud.github.com/assets/3960883/301131/f235b3e0-95bf-11e2-96e8-8944e4ff0a89.png)

**Comment by eyedol** [comment]
@manwinder  Please send me crash reports with [catlog](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat) if you don't mind

**Comment by manwinder** [comment]
I am not a techie. Can you please guide me how can I send you the catlog.

I filled in a crash report and submitted with Android however

**Comment by manwinder** [comment]
Downloaded catlog

Sending you a log (though I am not sure it is exactly what you need. Just
ran ushahidi again after downloading catlog and thereafter saved the result
that is attached here)

Regards
Manwinder Singh
Contact - +91 99700 51851

**Comment by manwinder** [comment]
@elle-espere @eyedol 

As per Kelli's suggestion I updated my ushahidi app version to 3.1.5
My deployment now works fine on my android phone. 

However, Kelli has a list of 4 other problems that needs to be solved.
Look forward to your support :)

**Comment by eyedol** [comment]
@manwinder  Glad to hear it's working.

Could you get Kelli to report the issues and include how I can reproduce them from my end? Thanks

**Comment by manwinder** [comment]
@elle-espere 

Hi Kelli, could you please co-ordinate with Henry about the other four problems as well
1. SMS Sync : Delay in outgoing alerts + Pending SMS (incoming) do not sync despite the correct URL etc.
2. Contact Us page - Throws an error message despite entering the correct verification code
3. Time difference on the 'Submit Report' page.

Thanks !

**Comment by ghost** [comment]
@manwinder Absolutely!  One has been up for 3 days in the Ushahidi web forum:: #2 :)

**Comment by ghost** [comment]
Thank you @eyedol for all your assistance to Manwinder and myself!

**Comment by ghost** [comment]
@aoduor This is the issue that has been resolved. @manwinder
